apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: demo-app-canary-success
  namespace: progressive-delivery
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: demo-app-v2
  service:
    port: 80
    name: demo-app
    gateways:
      - demo-gateway
    hosts:
      - "*"
  analysis:
    interval: 30s
    maxWeight: 100
    stepWeight: 20
    threshold: 1
    metrics:
      - name: request-success-rate
        thresholdRange:
          min: 1
        interval: 30s
      - name: request-duration
        thresholdRange:
          max: 10000
        interval: 30s
    webhooks:
      - name: load-test
        url: http://flagger-loadtester.progressive-delivery/
        timeout: 5s
        metadata:
          cmd: "hey -z 25s -q 10 -c 5 http://demo-app.progressive-delivery/"
